import { formatAiComment, formatManualComment } from '../../providers/base';

describe('Comment Formatters', () => {
  describe('formatAiComment', () => {
    it('should wrap body with AI comment header and footer', () => {
      const body = 'This PR looks good';
      const formatted = formatAiComment(body);

      expect(formatted).toContain('🤖 AI PR Review');
      expect(formatted).toContain('This PR looks good');
      expect(formatted).toContain('AI PR Reviewer');
      expect(formatted).toContain('automatically generated by an AI model');
    });

    it('should include HTML comment for detection', () => {
      const body = 'Test review';
      const formatted = formatAiComment(body);

      expect(formatted).toContain('<!-- ad-ai-pr-reviewer -->');
    });

    it('should preserve body content exactly', () => {
      const body = '**Bold** and *italic* text\n\nWith multiple paragraphs';
      const formatted = formatAiComment(body);

      expect(formatted).toContain(body);
    });

    it('should include link to GitHub repository', () => {
      const body = 'Review';
      const formatted = formatAiComment(body);

      expect(formatted).toContain('https://github.com/subzone/ad-ai-pr-reviewer');
    });
  });

  describe('formatManualComment', () => {
    it('should wrap body with manual comment header', () => {
      const body = 'Build passed, ready to merge';
      const formatted = formatManualComment(body);

      expect(formatted).toContain('💬 AI PR Comment');
      expect(formatted).toContain(body);
      expect(formatted).toContain('AI PR Reviewer');
    });

    it('should include HTML comment for detection', () => {
      const body = 'Test comment';
      const formatted = formatManualComment(body);

      expect(formatted).toContain('<!-- ad-ai-pr-reviewer -->');
    });

    it('should preserve body content exactly', () => {
      const body = '**Testing notes:**\n- Test 1\n- Test 2';
      const formatted = formatManualComment(body);

      expect(formatted).toContain(body);
    });

    it('should distinguish from AI comment', () => {
      const aiFormatted = formatAiComment('content');
      const manualFormatted = formatManualComment('content');

      expect(aiFormatted).toContain('🤖 AI PR Review');
      expect(manualFormatted).toContain('💬 AI PR Comment');
      expect(aiFormatted).not.toEqual(manualFormatted);
    });
  });
});
