export interface PullRequest {
  number: number;
  url: string;
  title: string;
  sourceBranch: string;
  targetBranch: string;
  diff?: string;
}

export interface CreatePROptions {
  repository: string;
  sourceBranch: string;
  targetBranch: string;
  title: string;
  description: string;
}

export interface PostCommentOptions {
  repository: string;
  prNumber: number;
  body: string;
}

export interface GetDiffOptions {
  repository: string;
  prNumber: number;
}

export interface ReviewComment {
  path: string;            // File path
  line: number;            // Line number in the new version
  body: string;            // Comment text
  suggestion?: string;     // Optional code suggestion
}

export interface PostReviewCommentsOptions {
  repository: string;
  prNumber: number;
  comments: ReviewComment[];
  commitId?: string;       // Optional: specific commit to comment on
}

export interface ProviderConfig {
  accessToken: string;
  serverUrl?: string;
}

export interface Provider {
  createPR(options: CreatePROptions): Promise<PullRequest>;
  findExistingPR(repository: string, sourceBranch: string, targetBranch: string): Promise<PullRequest | null>;
  postComment(options: PostCommentOptions): Promise<void>;
  getDiff(options: GetDiffOptions): Promise<string>;
  postReviewComments?(options: PostReviewCommentsOptions): Promise<void>;  // Optional for inline comments
}

export function formatAiComment(body: string): string {
  return [
    '<!-- ad-ai-pr-reviewer -->',
    '> **🤖 AI PR Review** &nbsp;|&nbsp; *Generated by [AI PR Reviewer](https://github.com/subzone/ad-ai-pr-reviewer) via Azure DevOps*',
    '',
    '---',
    '',
    body,
    '',
    '---',
    '*This comment was automatically generated by an AI model. Please review suggestions critically.*',
  ].join('\n');
}

export function formatManualComment(body: string): string {
  return [
    '<!-- ad-ai-pr-reviewer -->',
    '> **💬 AI PR Comment** &nbsp;|&nbsp; *Posted by [AI PR Reviewer](https://github.com/subzone/ad-ai-pr-reviewer) via Azure DevOps*',
    '',
    '---',
    '',
    body,
  ].join('\n');
}
